@startchen

entity User {
}

entity House {
}

entity Location {
    LocationType
}

entity Device {
}

entity DeviceAuthentication {
    url : STRING
    AuthMethod
    AuthCredentials
}

entity DeviceType {

}

entity DeviceProtocol {
}

entity DeviceCommand {
    DeviceCommandType
}

entity DeviceSpecification {

}


entity TelemetryData {
    TelemetryDataType
    value : STRING
}

User -(1,N)- House

House -(1,N)- Location
Device -- DeviceSpecification
Location -(1,N)- Device

DeviceSpecification -(1,N)- DeviceCommand
DeviceSpecification -- DeviceProtocol
DeviceSpecification -- DeviceType

DeviceAuthentication -- Device
TelemetryData -- Device


@endchen
