@startuml
title "Диаграмма контейнера Телеметрия приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Component.puml

System_Boundary(SmartHomeApp, "Приложения использующие API") {
    System(WebApp, "WebApp")
}

System_Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
}

System_Boundary(Domain, "Управление устройствами умного дома") {
    Container_Boundary(SubdomainTelemetry, "Телеметрия") {
        Component(TelemetryApi, "API")
        Component(TelemetryScheduler, "Scheduler")
        ComponentDb(TelemetryDb, "DB")
        ComponentQueue(TelemetryQueue, "Queue")
    }

    Container_Boundary(SubdomainAdministration, "Администрирование") {
        Component(AdministrationApi, "API")
        ComponentDb(AdministrationDb, "DB")
    }

}


Rel(TelemetryApi, TelemetryDb, "Read\Write")
Rel(TelemetryApi, TelemetryQueue, "Запрашивает данные", "Состояние датчика")
Rel(TelemetryQueue, TelemetryDb, "Read\Write")

Rel(SensorHeating, TelemetryApi, "Отправляет данные", "Датчик")
Rel(TelemetryQueue, SensorHeating, "Запрос к датчику", "Узнать состояние")

Rel(AdministrationDb, TelemetryDb, "Replication")
Rel(AdministrationApi, TelemetryApi, "Запрашивает данные", "Для отчетов телеметрии")
Rel(WebApp, AdministrationApi, "Запрашивает данные", "Для отчетов телеметрии")

Rel(TelemetryScheduler, TelemetryQueue, "Запрашивает данные", "Состояние датчика")


@enduml

