@startuml
title "Диаграмма контейнера Телеметрия приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Component.puml

System_Boundary(SmartHomeApp, "Приложения использующие API") {
    System(WebApp, "WebApp")
}

Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
}

System_Boundary(Domain, "Управление устройствами умного дома") {
    System_Boundary(SubdomainTelemetry, "Телеметрия") {
        Container_Boundary(TelemetryApi, "API") {
            Component("TelemetryController", "Возвращает данные телеметрии", "SpringWeb Controller")
            Component("DeviceStateController", "Возвращает состояние устройства", "SpringWeb Controller")
            Component("DeviceDataReceiverController", "Прием состояния устройства", "SpringWeb Controller")
        }

        Container(TelemetryScheduler, "Scheduler")
        ContainerDb(TelemetryDb, "DB")
        ContainerQueue(TelemetryQueue, "Queue")
    }

    System_Boundary(SubdomainManageDevice, "Управление устройствами") {
        Container(ManageDeviceApi, "API")
    }

    System_Boundary(SubdomainAdministration, "Администрирование") {
        Container(AdministrationApi, "API")
    }

}


Rel(WebApp, AdministrationApi, "Запрашивает данные", "Для отчетов телеметрии")

Rel(TelemetryController, TelemetryDb, "Read")
Rel(DeviceStateController, TelemetryDb, "Read")
Rel(DeviceDataReceiverController, TelemetryDb, "Read\Write")

Rel(DeviceStateController, TelemetryQueue, "Запрашивает данные", "Состояние устройства")
Rel(TelemetryQueue, TelemetryDb, "Read\Write")

Rel(SensorHeating, TelemetryApi, "Отправляет данные", "Устройство")
Rel(TelemetryQueue, SensorHeating, "Запрос к датчику", "Узнать состояние")

Rel(AdministrationDb, TelemetryDb, "Replication")
Rel(AdministrationApi, TelemetryController, "Запрашивает данные", "Для отчетов телеметрии")
Rel(ManageDeviceApi, TelemetryController, "Запрашивает данные", "Состояние устройства")
Rel(ManageDeviceApi, DeviceDataReceiverController, "Отправляет данные", "Состояние устройства")

Rel(TelemetryScheduler, TelemetryQueue, "Запрашивает данные", "Состояние устройства")

@enduml

