@startuml
title "Диаграмма контейнера Телеметрия приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Container.puml


System_Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
    System(SensorLight, "Датчик света на крыльце")
}

System_Boundary(SubdomainTelemetry, "Поддомен: Телеметрия") {
    System(TelemetryApi, "API")
    SystemDb(TelemetryDb, "DB")
    SystemQueue(TelemetryQueue, "Queue")
}

ContainerDb_Ext(AdministrationDb, "DB Администрирование")
Container_Ext(ManageDeviceApi, "API Управление устройствами")

Rel(TelemetryApi, TelemetryDb, "Read\Write")
Rel(TelemetryApi, TelemetryQueue, "Add To")
Rel(TelemetryQueue, TelemetryDb, "Read")

Rel(SensorLight, TelemetryApi, "Отправляет данные")
Rel(TelemetryApi, SensorLight, "Запрашивает данные")

Rel(SensorHeating, TelemetryApi, "Отправляет данные")
Rel(TelemetryApi, SensorHeating, "Запрашивает данные")

Rel(AdministrationDb, TelemetryDb, "Replication")
Rel(ManageDeviceApi, TelemetryApi, "Запрашивает данные")



@enduml

