@startuml
title "Диаграмма контейнера Управление устройствами приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Component.puml

System_Boundary(SmartHomeApp, "Приложения использующие API") {
    System(WebApp, "WebApp")
}

System_Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
}


System_Boundary(Domain, "Управление устройствами умного дома") {
    System_Boundary(SubdomainManageDevice, "Управление устройствами") {
        Container(ManageDeviceApi, "API")
        ContainerDb(ManageDeviceDb, "DB")
        ContainerQueue(ManageDeviceQueue, "Queue")
    }

    System_Boundary(SubdomainAdministration, "Администрирование") {
        Container(AdministrationApi, "Api")
        ContainerDb(AdministrationDb, "DB")
    }
}



Rel(AdministrationDb, ManageDeviceDb, "Replication")
Rel(ManageDeviceQueue, ManageDeviceDb, "Read/Write")

Rel(AdministrationApi, ManageDeviceApi, "Отправляет команду", "Для устройства")

Rel(ManageDeviceApi, ManageDeviceQueue, "Добавляет команду в очередь")
Rel(ManageDeviceQueue, SensorHeating, "Отправляет команду", "Датчику")
Rel(ManageDeviceQueue, SensorHeating, "Запрашивает данные", "Состояния датчика")

Rel(WebApp, AdministrationApi, "Отправляет команду", "Для устройства")



@enduml

