@startuml
title "Диаграмма контекста приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Container.puml

Person(User, "Пользователь")
Person(Specialist, "Специалист компании", "", person2)

System_Boundary(SmartHomeApp, "Приложения использующие API") {
    System(WebApp, "WebApp")
}

Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
}


System_Boundary(Domain, "Управление устройствами умного дома") {
    System_Boundary(SubdomainTelemetry, "Телеметрия") {
        Container(TelemetryApi, "API")
        Container(TelemetryScheduler, "Scheduler")
        ContainerDb(TelemetryDb, "DB")
        ContainerQueue(TelemetryQueue, "Queue")
    }

    System_Boundary(SubdomainAdministration, "Администрирование") {
        Container(AdministrationApi, "API")
        ContainerDb(AdministrationDb, "DB")
    }

    System_Boundary(SubdomainManageDevice, "Управление устройствами") {
        Container(ManageDeviceApi, "API")
        ContainerDb(ManageDeviceDb, "DB")
        ContainerQueue(ManageDeviceQueue, "Queue")
    }

}


Rel(Specialist, WebApp, "Управляет данными")
Rel(User, WebApp, "Управляет данными")
Rel(WebApp, AdministrationApi, "Управляет данными")
Rel(WebApp, AdministrationApi, "Отправляет команду", "Для устройства")
Rel(WebApp, AdministrationApi, "Запрашивает данные", "Для отчетов телеметрии")

Rel(AdministrationApi, AdministrationDb, "Read\Write")
Rel(AdministrationApi, TelemetryApi, "Запрашивает данные", "Отчеты, состояние датчика")
Rel(AdministrationApi, ManageDeviceApi, "Отправляет команду", "Для устройства")
Rel(AdministrationDb, TelemetryDb, "Replication")
Rel(AdministrationDb, ManageDeviceDb, "Replication")

Rel(TelemetryApi, TelemetryDb, "Read\Write")
Rel(TelemetryApi, TelemetryQueue, "Запрашивает данные", "Состояние датчика")
Rel(TelemetryQueue, TelemetryDb, "Read\Write")
Rel(TelemetryQueue, SensorHeating, "Запрос к датчику", "Узнать состояние")
Rel(TelemetryScheduler, TelemetryQueue, "Запрашивает данные", "Состояние датчика")


Rel(ManageDeviceApi, ManageDeviceQueue, "Добавляет команду в очередь")
Rel(ManageDeviceQueue, ManageDeviceDb, "Read/Write")
Rel(ManageDeviceQueue, SensorHeating, "Отправляет команду", "Датчику")
Rel(ManageDeviceQueue, SensorHeating, "Запрашивает данные", "Состояния датчика")

Rel(SensorHeating, TelemetryApi, "Отправляет данные", "Датчик")


@enduml

