@startuml
title "Диаграмма контекста приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Context.puml

Person(User, "Пользователь")
Person(Specialist, "Специалист компании", "", person2)

System_Boundary(SmartHomeApp, "Приложения использующие API") {
    System(WebApp, "WebApp")
}

System_Boundary(SmartHomeApi, "Smart Home API") {
    System(Administration, "Администрирование")
    System(Telemetry, "Телеметрия")
    System(ManageDevice, "Управление устройствами")
}

System_Boundary(UserHome, "Дом пользователя") {
    System(SensorHeating, "Датчик отопления")
}


Rel(User, WebApp, "Управляет данными и устройствами")
Rel(Specialist, WebApp, "Управляет данными и устройствами")

Rel(WebApp, Administration, "Управляет данными и устройствами")

Rel(Administration, Telemetry, "Получение данных телеметрии и состояние устройств")
Rel(Administration, ManageDevice, "Отправка команд устройству")

Rel(Telemetry, SensorHeating, "Получение состояния устройства")
Rel(SensorHeating, Telemetry, "Отправка состояния устройства")
Rel(ManageDevice, SensorHeating, "Отправка команд устройству")



@enduml

