@startuml
title "Диаграмма контейнера Администрирование приложения Smart Home To Be"

top to bottom direction

!include C4/C4_Container.puml

Person(User, "Пользователь")
Person(Specialist, "Специалист компании", "", person2)

System_Boundary(Domain, "Управление устройствами умного дома") {
    Container_Boundary("Administration", "Администрирование") {
        Container(AdministrationApi, "API")
        ContainerDb(AdministrationDb, "DB")
    }

    Container_Boundary(SubdomainManageDevice, "Управление устройствами") {
        Container(ManageDeviceApi, "API")
    }

    Container_Boundary(SubdomainTelemetry, "Телеметрия") {
        Container(TelemetryApi, "API")
    }
}

Rel(AdministrationApi, AdministrationDb, "Read\Write")
Rel(AdministrationApi, TelemetryApi, "Запрашивает данные", "Отчеты, состояние датчика")
Rel(AdministrationApi, ManageDeviceApi, "Отправить команду", "Датчику")

Rel(Specialist, AdministrationApi, "Управляет данными")
Rel(User, AdministrationApi, "Управляет данными")


@enduml

